#include "init/init.hpp"
#include "init/init.cpp"
#include "init/module/manager.cpp"
#include "init/module/manager.hpp"
#include "init/module/init.cpp"
#include "init/module/init.hpp"
#include "init/modules.hpp"
#include "init/driver/init.cpp"
#include "init/driver/init.hpp"
#include "init/driver/manager.cpp"
#include "init/driver/manager.hpp"
#include "init/drivers.hpp"
#include "init/routine/init.cpp"
#include "init/routine/init.hpp"
#include "init/routine/manager.hpp"
#include "init/routine/manager.cpp"
#include "init/routines.hpp"
#include "init/dictonary/init.cpp"
#include "init/dictonary/init.hpp"
#include "init/dictonary/manager.cpp"
#include "init/dictonary/manager.hpp"
#include "init/dictonary/ctransl.cpp"
#include "init/dictonary/ctransl.hpp"
#include "init/dictonaries.hpp"
#include "init/communication/init.cpp"
#include "init/communication/init.hpp"
#include "init/communication/manager.cpp"
#include "init/communication/manager.hpp"
#include "init/communication/netinit.cpp"
#include "init/communication/netinit.hpp"
#include "init/communication/dispinit.cpp"
#include "init/communication/dispinit.hpp"
#include "init/communication/modinit.cpp"
#include "init/communication/modinit.hpp"
#include "init/communication/soundinit.cpp"
#include "init/communication/soundinit.hpp"
#include "init/output/init.cpp"
#include "init/output/init.hpp"
#include "init/output/handler.cpp"
#include "init/output/handler.hpp"
#include "init/sensory/init.cpp"
#include "init/sensory/init.hpp"
#include "init/sensory/handler.cpp"
#include "init/sensory/handler.hpp"
#include "init/sensory/manager.cpp"
#include "init/sensory/manager.hpp"
#include "init/sensory/monitor.cpp"
#include "init/sensory/monitor.hpp"

#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfenv>
#include <cfloat>
#include <cinttypes>
#include <ciso646>
#include <climits>
#include <clocale>
#include <cmath>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstdbool>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctgmath>
#include <ctime>
#include <cuchar>
#include <cwchar>
#include <cwctype>

#include <array>
#include <deque>
#include <forward_list>
#include <list>
#include <map>
#include <queue>
#include <set>
#include <stack>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <fstream>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <ostream>
#include <sstream>
#include <streambuf>

#include <atomic>
#include <condition_variable>
#include <future>
#include <mutex>
#include <thread>

#include <algorithm>
#include <bitset>
#include <chrono>
#include <codecvt>
#include <complex>
#include <exception>
#include <functional>
#include <initializer_list>
#include <iterator>
#include <limits>
#include <locale>
#include <memory>
#include <new>
#include <numeric>
#include <random>
#include <ratio>
#include <regex>
#include <stdexcept>
#include <string>
#include <system_error>
#include <tuple>
#include <typeindex>
#include <typeinfo>
#include <type_traits>
#include <utility>
#include <valarray>